(function() {var implementors = {};
implementors['terminal_cli'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='terminal_cli/enum.AutocompleteOption.html' title='terminal_cli::AutocompleteOption'>AutocompleteOption</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='terminal_cli/enum.AutocompleteResult.html' title='terminal_cli::AutocompleteResult'>AutocompleteResult</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='terminal_cli/struct.AutocompleteLine.html' title='terminal_cli::AutocompleteLine'>AutocompleteLine</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='terminal_cli/enum.AutocompleteOption.html' title='terminal_cli::AutocompleteOption'>AutocompleteOption</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='terminal_cli/enum.AutocompleteResult.html' title='terminal_cli::AutocompleteResult'>AutocompleteResult</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='terminal_cli/struct.AutocompleteLine.html' title='terminal_cli::AutocompleteLine'>AutocompleteLine</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
